spring:
  application:
    name: binance

server:
  port: ${PORT:8080}
  address: 0.0.0.0


clients:
  binance:
    websocket:
      url: wss://stream.binance.com:9443

logging:
  level:
    root: INFO
    reactor.netty.http.client: DEBUG
    reactor.netty.tcp: DEBUG
    com.webflux.binance.client: DEBUG
    com.webflux.binance.handler: DEBUG